# Site settings
title: "Currículo Digital"
description: "Currículo Digital - William Torres Araujo"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "false"
resume_name:                    "William Torres Araujo"
resume_title:                   "Estudante autodidata de programação no 3º Ensino Médio"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "william.mine64@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "(11)984413154"
resume_contact_address:         "Rua Ribeiro de Barros"

resume_header_contact_info:     "Rua Ribeiro de Barros • SP • 07/05/2005 • 11984413154 • william.mine64@gmail.com"
display_header_contact_info:    "true"

resume_header_intro: "<p>Estou empenhado em aprender continuamente, crescer profissionalmente e aplicar meu potencial para fazer contribuições valiosas à minha equipe e organização.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
#resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
# resume_section_recognition:     false
#resume_section_links:           false
# resume_section_associations:    false
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
#resume_social_links:
  #resume_github_url:            "https://github.com/jglovier/resume-template"
  #resume_twitter_url:           "http://twitter.com/jglovier"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  #resume_linkedin_url:          "https://www.linkedin.com/in/joelglovier"
  # resume_instagram_url:         "insert your Instagram URL here"
  #resume_website_url:           "http://joelglovier.com"
  #resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      false

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
